version: "3"
services:
  app:
    restart: always
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whysapi
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: whysapi.local_settings
      DJANGO_DEBUG: "True"
      DEBUG: "True"
      ENV: "LOCAL"
      DJANGO_SECRET_KEY: "dev_7xpg#83-k9w82mm%bu3*)g8qqvp(_-6mrsu$nc3)*iujvcgo2&_elop"
    privileged: true

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=whysapi
      - POSTGRES_USER=whysapi
      - POSTGRES_PASSWORD=whysapi
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
